export var color_white = '#fff'
export var color_black = '#000000'
export var color_transparent = 'transparent'
export var color_purple_dark = '#172C4B'
export var color_purple_light = '#5F4B9B'
export var color_green = '#54c79f'